### PR TITLE
JOSS paper

### PR DESCRIPTION
**Pull request by anowacki**
This branch contains an up to date version of the JOSS paper manuscript.

### CODE REVIEW

**Comment by bobmyhill** [comment]
Hi @anowacki, I rebased this PR with some of @daviesjh2 changes on main. That has broken the history, so you'll need to rebase on your local machine if you made any more changes.

To prevent this happening again, I protected this branch so that we have to open PRs to merge onto it. I think it makes sense that we keep this as our main paper branch during review.

**Comment by anowacki** [comment]
Thanks, Bob.  Closing this now.

Others—please now open pull requests against `joss-paper`.

**Comment by jamespanton93** [comment]
The pull request that I just merged into main seems to have been affected by this, do I need to merge changes from `joss-paper` into main to fix this?

**Comment by anowacki** [comment]
Not to worry, @jamespanton93, we can merge the branch in when needed.  But if future changes could be against `joss-paper` that would be ideal.

**Pull request closed without merging**
